### ISSUE TITLE
Write value back to cpu

### ISSUE THREAD

**Issue by helson22** [dixi83/hassio-addons#53]
Hi there :-)

In the cpu there is a real value I sent to HA with the addon. 
First I read this like a normal sensor.
```
  - name: Temp_House
    type: sensor
    state: DB56,REAL6
```

Now I want to modify this value using a input number slider in the dashboard and write it back to the cpu.
Is this the right code for my problem? 
```
state:
  plc: DB56,REAL6,
  set_plc: DB56,REAL6,
  write_back: true
```
Can both references be the same here? (DB56.REAL6)

Thx in advance!

**Comment by helson22** [comment]
Hello,

can you help me pls? 

Thank you!

**Comment by dixi83** [comment]
Sorry for the delay, I was working on a different project. 
A `sensor` is read-only. We need a `number` here but, the add-on is missing the `number` entity type. I need to develop this... this might take some time. 

- [ ] @dixi83 develop `number`

**Comment by helson22** [comment]
Ok thanks for your reply - sorry for bothering you with this.
Good to hear your work will go on.  :-)

**Comment by dixi83** [comment]
Hey, I just added the number device the configuration structure will bee like this.
```yaml
  - name: Number with min max and step
    type: number
    state: DB999,REAL2
    device_name: NumberTest 123
    min: 0
    max: 12
    step: 0.5
```
Please test it, let me know if it works or if you have issues.
