### ISSUE TITLE
Bug in 1.0.8 reading bits?

### ISSUE THREAD

**Issue by helson22** [dixi83/hassio-addons#64]
Hi,

I just updated to new 1.0.8 but this:

```
devices:
  - name: window1
    type: sensor
    **state: DB3,X0.0**
    device_name: room1
```

OR this
```

devices:
  - name: window1
    type: sensor
    **state: DB3,DBX0.0**
    device_name: room1
```

Also some real values could not be read.
```

  - name: temp1
    type: sensor
    state: DB11,REAL2
    device_name: outside
```

I have three config files (yamls). Log is fine - no errors!
It seems two of the three have the problems - changed nothing to them.

The first only reads bit-values and one int (last entry). The second seems fine - mixed bool and real. Th third is also mixed with bool and real.
DB3
![1](https://github.com/user-attachments/assets/1450cd03-ad60-4a8c-95f8-c3e7a9d4eede)
DB11
![2](https://github.com/user-attachments/assets/073be534-0ecc-4d5f-a5e4-5529e37f0748)
DB5
![3](https://github.com/user-attachments/assets/8e1a7542-17a9-4733-9920-fe2517b32eb6)

Home Assitant Core 2025.1.0 - installed an hour ago.

I restored the addon-Backup to 1.0.6 and all is fine.

Pls have a look.

thx

**Comment by helson22** [comment]
Ok, I played around with the yaml.

I'm not sure, bute is it possible that the 

`device:`

or 

`device_name:`

can have an impact on this strange behaviour?

**Comment by helson22** [comment]
Or ist this a delay on the MQTT?

**Comment by dixi83** [comment]
It should be `device_name`. This is not changed.

Here it is al working. Although I noticed some delay as well. Trying to get my finger on it. 

Have you checked the logs? If not, next time please do so and report errors you see here. There is a new feature that checks your YAML for mistakes! it probably gives you some hints, although they could be a bit confusing.

In my case it gave my this error and the add-on stopped.
```
  {
    instancePath: '/devices/5/state',
    schemaPath: '#/properties/devices/items/allOf/0/then/properties/state/oneOf/1/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'unit_of_measurement' },
    message: 'must NOT have additional properties'
  },
```

I had a mistake  in the `state:`  of the 5(+1)th  section:
```yaml
    state: 
        plc: DB31,REAL4
        update_interval: 10000
        unit_of_measurement: mm
```
In the new situation we do not accept `unit_of_measurement` any more in this section. this was my mistake as well. it needs to be 1 level lower. Like this
```yaml
  - name: Drumfilter level
    type: sensor
    state: 
        plc: DB31,REAL4
        update_interval: 10000
    unit_of_measurement: mm
    device_name: Pond Drum filter
```

Hope this helps.
