### ISSUE TITLE
device type: number

### ISSUE THREAD

**Issue by helson22** [dixi83/hassio-addons#70]
Hello guys,

I have [problems ](https://github.com/dixi83/hassio-addons/issues/53#issuecomment-2585899425) to integrate the new device-type number.

With the following I get a entity with the name number.heating_room

```
  - name: HEATING_ROOM
    type: number
    state: DB4,REAL0
    min: 19
    max: 24
    step: 0.5
```

There are two issues. The first is more add-on related, the second I think more home assistant, but I can't find the right approach to work with the numer device type at all.

1.

I placed the two concerned entities in the dashboard where HEATING_ROOM is the PLC value and the "Sollwert Haus" is the input number helper from HA.

![13-01-2025_13-27-51](https://github.com/user-attachments/assets/2bb69ab1-3903-4c50-a218-a5c406b7974c)

The issue is that if i manipulate the value for HEATING_ROOM via the slider, no value is changed (22 stands still) the slider displays the value where I dropped it (24 in the screenshot). Then nothing is changed in the PLC. Can you confirm this behaviour?  How do do change the value in HA? Where can the mistake be here? I played around a long time but can't find it.

___________

2.

Why do I want the input helper? A input box, for me is more, let's say "user stable", to change the concerning value. With sliders and a small touchscreen maybe you do something unintentionally. So that's why I prefer inputbox with +/- arrows or input the value via keyboard. 
![13-01-2025_13-01-45](https://github.com/user-attachments/assets/b5a23a1b-df29-4e60-a04e-4c0ea1d1aa0d)

Unfortunately the slider from number.heating_room, which comes from the plc via the add-on, can't be changed to input box. Secondly, I can configure decimal places (steps) in the add-on yaml config. The slider from number.heating_room only change integer.
![13-01-2025_13-38-33](https://github.com/user-attachments/assets/da721676-0ef1-437e-b891-bcebec16ecc4)

The question is, can we get rid of this input number helper, or will it be possible that the addon "configures" the entity with the options a input number helper provides? (min, max, step, unit of measurement)

I tried to change the plc entity with the input number helper via an automation, which doesn't work. Maybe section 1 and 2 of this post are "connected". The automation triggers but changes nothing.

```
id: '1736681584524'
alias: test sollwert haus
description: ''
triggers: []
conditions: []
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: '{{states(''input_number.sollwert_haus'')}}'
    target:
      entity_id: number.heating_room
mode: single
```

Thank you in advance!
BR
